version: "3.8"

x-networkfit:
  &NETWORKFIT
  network: host
  args:
    http_proxy: $http_proxy
    https_proxy: $https_proxy

services:
  ####
  dc-gate-server:
    build:
      context: ./dev-gate-server
      dockerfile: Dockerfile
      << : *NETWORKFIT
    image: "${ENV_CI_DOCKER_USERNAME:-neozxin}/dev-gate-server:${ENV_CI_DOCKERIMAGE_THISTAG:-latest}"
    restart: unless-stopped
    ports:
      - "443:443"
    extra_hosts:
      - "host.mydocker.local:${ENV_DOCKERC_HOST:-172.17.0.1}"
  ####
  dc-desktop-terminal:
    build:
      context: ./dev-desktop-terminal
      dockerfile: Dockerfile
      << : *NETWORKFIT
    image: "${ENV_CI_DOCKER_USERNAME:-neozxin}/dev-desktop-terminal:${ENV_CI_DOCKERIMAGE_THISTAG:-latest}"
    restart: unless-stopped
    ports:
      - "15900:5900"
      - "16080:6080"
      - "17681:7681"
    extra_hosts:
      - "host.mydocker.local:${ENV_DOCKERC_HOST:-172.17.0.1}"
  ####
  dc-desktop-x11vnc:
    build:
      context: ./dev-desktop-x11vnc
      dockerfile: Dockerfile
      << : *NETWORKFIT
    image: "${ENV_CI_DOCKER_USERNAME:-neozxin}/dev-desktop-x11vnc:${ENV_CI_DOCKERIMAGE_THISTAG:-latest}"
    restart: unless-stopped
    ports:
      - "5900:5900"
    extra_hosts:
      - "host.mydocker.local:${ENV_DOCKERC_HOST:-172.17.0.1}"
